sonar.projectKey=Secure-Python-DevSecOps
sonar.projectName=Secure Python DevSecOps

sonar.host.url=http://localhost:9000

sonar.sources=app
sonar.tests=tests
sonar.python.version=3.12
sonar.sourceEncoding=UTF-8

sonar.scanner.arch=aarch64
